package com.tch.test.guice_jersey_mybatis_test.model;

public class Account {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.id
     *
     * @mbg.generated Thu Sep 07 16:26:39 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.password
     *
     * @mbg.generated Thu Sep 07 16:26:39 CST 2017
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.chinese_name
     *
     * @mbg.generated Thu Sep 07 16:26:39 CST 2017
     */
    private String chineseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.english_name
     *
     * @mbg.generated Thu Sep 07 16:26:39 CST 2017
     */
    private String englishName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.avatar
     *
     * @mbg.generated Thu Sep 07 16:26:39 CST 2017
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.email
     *
     * @mbg.generated Thu Sep 07 16:26:39 CST 2017
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.mobile
     *
     * @mbg.generated Thu Sep 07 16:26:39 CST 2017
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.hobby
     *
     * @mbg.generated Thu Sep 07 16:26:39 CST 2017
     */
    private String hobby;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.id
     *
     * @return the value of account.id
     *
     * @mbg.generated Thu Sep 07 16:26:39 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.id
     *
     * @param id the value for account.id
     *
     * @mbg.generated Thu Sep 07 16:26:39 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.password
     *
     * @return the value of account.password
     *
     * @mbg.generated Thu Sep 07 16:26:39 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.password
     *
     * @param password the value for account.password
     *
     * @mbg.generated Thu Sep 07 16:26:39 CST 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.chinese_name
     *
     * @return the value of account.chinese_name
     *
     * @mbg.generated Thu Sep 07 16:26:39 CST 2017
     */
    public String getChineseName() {
        return chineseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.chinese_name
     *
     * @param chineseName the value for account.chinese_name
     *
     * @mbg.generated Thu Sep 07 16:26:39 CST 2017
     */
    public void setChineseName(String chineseName) {
        this.chineseName = chineseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.english_name
     *
     * @return the value of account.english_name
     *
     * @mbg.generated Thu Sep 07 16:26:39 CST 2017
     */
    public String getEnglishName() {
        return englishName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.english_name
     *
     * @param englishName the value for account.english_name
     *
     * @mbg.generated Thu Sep 07 16:26:39 CST 2017
     */
    public void setEnglishName(String englishName) {
        this.englishName = englishName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.avatar
     *
     * @return the value of account.avatar
     *
     * @mbg.generated Thu Sep 07 16:26:39 CST 2017
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.avatar
     *
     * @param avatar the value for account.avatar
     *
     * @mbg.generated Thu Sep 07 16:26:39 CST 2017
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.email
     *
     * @return the value of account.email
     *
     * @mbg.generated Thu Sep 07 16:26:39 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.email
     *
     * @param email the value for account.email
     *
     * @mbg.generated Thu Sep 07 16:26:39 CST 2017
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.mobile
     *
     * @return the value of account.mobile
     *
     * @mbg.generated Thu Sep 07 16:26:39 CST 2017
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.mobile
     *
     * @param mobile the value for account.mobile
     *
     * @mbg.generated Thu Sep 07 16:26:39 CST 2017
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.hobby
     *
     * @return the value of account.hobby
     *
     * @mbg.generated Thu Sep 07 16:26:39 CST 2017
     */
    public String getHobby() {
        return hobby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.hobby
     *
     * @param hobby the value for account.hobby
     *
     * @mbg.generated Thu Sep 07 16:26:39 CST 2017
     */
    public void setHobby(String hobby) {
        this.hobby = hobby;
    }
}